services:
  nginx:
    build:
      context: ./nginx
      dockerfile: ./docker/Dockerfile
    image: ft_nginx
    container_name: ft_nginx
    ports:
      - 8443:443
    networks:
      - ft_network
    env_file:
      - ./nginx/.env.local
    depends_on:
      - frontend
      - be_common
  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    image: ft_frontend
    container_name: ft_frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      NODE_ENV: development
    env_file:
      - ./frontend/.env.local
    networks:
      - ft_network
    command: npm run dev
  be_common:
    build:
      context: ./backends/common
      dockerfile: ./docker/Dockerfile
    image: ft_be_common
    container_name: ft_be_common
    volumes:
      - ./backends/common:/app
      - /app/node_modules
      - /app/dist
    environment:
      NODE_ENV: development
    env_file:
      - ./backends/common/.env.development
    ports:
      - 8080:8080
    networks:
      - ft_network
networks:
  ft_network:
    driver: bridge
