services:
  nginx:
    build:
      context: ./nginx
      dockerfile: ./docker/Dockerfile
    image: ft_nginx
    container_name: ft_nginx
    ports:
      - 8443:443
    networks:
      - ft_network
    env_file:
      - ./nginx/.env.local
    depends_on:
      - frontend
      - be_common
  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile.dev
    image: ft_frontend
    container_name: ft_frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      NODE_ENV: development
    env_file:
      - ./frontend/.env.local
    networks:
      - ft_network
    command: ${FE_CMD:-}
  be_common:
    build:
      context: ./backends/common
      dockerfile: ./docker/Dockerfile.dev
    image: ft_be_common
    container_name: ft_be_common
    volumes:
      - ./backends/common:/app
      - /app/node_modules
      - /app/dist
    environment:
      NODE_ENV: development
    env_file:
      - ./backends/common/.env.development
    ports:
      - 8080:80
    networks:
      - ft_network
    command: ${BE_COM_CMD:-}
  be_game:
    build:
      context: ./backends/game
      dockerfile: ./docker/Dockerfile.dev
    image: ft_be_game
    container_name: ft_be_game
    volumes:
      - ./backends/game:/app
      - /app/node_modules
      - /app/dist
    environment:
      NODE_ENV: development
    env_file:
      - ./backends/game/.env.development
    ports:
      - 8081:80
    networks:
      - ft_network
    command: ${BE_GM_CMD:-}
  be_text_chat:
    build:
      context: ./backends/text_chat
      dockerfile: ./docker/Dockerfile.dev
    image: ft_be_text_chat
    container_name: ft_be_text_chat
    volumes:
      - ./backends/text_chat:/app
      - /app/node_modules
      - /app/dist
    environment:
      NODE_ENV: development
    env_file:
      - ./backends/text_chat/.env.development
    ports:
      - 8082:80
    networks:
      - ft_network
    command: ${BE_TC_CMD:-}
networks:
  ft_network:
    driver: bridge
